services:
  tu02-step-ca:
    image: smallstep/step-ca:latest
    container_name: tu02-step-ca
    stdin_open: true
    tty: true
    ports:
      - 9000:9000
    volumes:
      - /usr/local/bin/just:/usr/local/bin/just:ro
      - ./justfile:/home/step/justfile:ro
      - ./certs:/home/step/certs:rw
      - ./config:/home/step/config:rw
      - ./db:/home/step/db:rw
      - ./letsencrypt/etc/letsencrypt:/home/step/letsencrypt
      - ./nginx/initial-certs:/tmp/initial-certs:rw
      - ./scripts:/home/step/scripts:ro
      - ./secrets:/home/step/secrets:rw
    command: /bin/sh
    network_mode: host
